# Generated by Django 5.1.7 on 2025-05-14 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_datetime',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reminder',
            name='delivery_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(),
        ),
    ]
